# Generated by Django 2.1.2 on 2018-12-11 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default="'docker'", max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default="'docker'", max_length=20)),
                ('ID', models.UUIDField(db_column='content_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('description', models.TextField(db_column='description')),
                ('image_url', models.TextField(db_column='image_url')),
                ('activity_level', models.ManyToManyField(to='demographics.ActivityLevel')),
                ('age_level', models.ManyToManyField(to='demographics.AgeLevel')),
                ('alcohol_status', models.ManyToManyField(to='demographics.AlcoholStatus')),
                ('complications', models.ManyToManyField(to='diseases.Complication')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default="'docker'", max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default="'docker'", max_length=20)),
                ('ID', models.AutoField(db_column='content_type_id', primary_key=True, serialize=False)),
                ('value', models.TextField(db_column='value', unique=True)),
            ],
            options={
                'db_table': 'content_type',
            },
        ),
        migrations.CreateModel(
            name='SharePeriod',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default="'docker'", max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default="'docker'", max_length=20)),
                ('ID', models.AutoField(db_column='share_period_id', primary_key=True, serialize=False)),
                ('start_date_interval', models.DurationField(db_column='min_date_interval')),
                ('end_date_interval', models.DurationField(db_column='max_date_interval')),
            ],
            options={
                'db_table': 'share_period',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(db_column='content_type', on_delete=django.db.models.deletion.PROTECT, to='content.ContentType'),
        ),
        migrations.AddField(
            model_name='content',
            name='diseases',
            field=models.ManyToManyField(to='diseases.Disease'),
        ),
        migrations.AddField(
            model_name='content',
            name='gender',
            field=models.ManyToManyField(to='demographics.Gender'),
        ),
        migrations.AddField(
            model_name='content',
            name='race',
            field=models.ManyToManyField(to='demographics.Race'),
        ),
        migrations.AddField(
            model_name='content',
            name='reading_level',
            field=models.ManyToManyField(to='demographics.ReadingLevel'),
        ),
        migrations.AddField(
            model_name='content',
            name='share_period',
            field=models.ForeignKey(db_column='share_period_id', on_delete='PROTECT', to='content.SharePeriod'),
        ),
        migrations.AddField(
            model_name='content',
            name='smoking_status',
            field=models.ManyToManyField(to='demographics.SmokingStatus'),
        ),
    ]
