# Generated by Django 2.1.2 on 2018-11-15 00:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default="'docker'", max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default="'docker'", max_length=20)),
                ('ID', models.UUIDField(db_column='complication_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(db_column='value')),
            ],
            options={
                'db_table': 'complication',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default="'docker'", max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default="'docker'", max_length=20)),
                ('ID', models.UUIDField(db_column='disease_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(db_column='title')),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.AddField(
            model_name='complication',
            name='disease',
            field=models.ForeignKey(db_column='disease_id', on_delete='PROTECT', to='diseases.Disease'),
        ),
    ]
