# Generated by Django 2.1.2 on 2018-11-26 18:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeIntervalRange',
            fields=[
                ('row_create_ts', model_utils.fields.AutoCreatedField(db_column='row_create_ts', default=django.utils.timezone.now, editable=False)),
                ('row_lup_ts', model_utils.fields.AutoLastModifiedField(db_column='row_lup_ts', default=django.utils.timezone.now, editable=False)),
                ('row_end_ts', models.DateTimeField(db_column='row_end_ts', default='9999-12-31 00:00:00.00000-00')),
                ('row_ef', models.BooleanField(db_column='row_ef', default=True)),
                ('row_create_usr_id', models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20)),
                ('row_lup_usr_id', models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20)),
                ('ID', models.AutoField(db_column='time_interval_range_id', primary_key=True, serialize=False)),
                ('start_date_interval', models.DurationField(db_column='min_date_interval')),
                ('end_date_interval', models.DurationField(db_column='max_date_interval')),
            ],
            options={
                'db_table': 'time_interval_range',
            },
        ),
        migrations.AlterField(
            model_name='activitylevel',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylevel',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='agelevel',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='agelevel',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='alcoholstatus',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='alcoholstatus',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='gender',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='gender',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='readinglevel',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='readinglevel',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='smokingstatus',
            name='row_create_usr_id',
            field=models.CharField(db_column='row_create_usr_id', default='dockerbash', max_length=20),
        ),
        migrations.AlterField(
            model_name='smokingstatus',
            name='row_lup_usr_id',
            field=models.CharField(db_column='row_lup_usr_id', default='dockerbash', max_length=20),
        ),
    ]
