# Generated by Django 2.1.2 on 2018-11-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_auto_20181126_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeIntervalRange',
        ),
    ]
